// Generated by tonic-build from `proto/peer.proto`. Lints below are scoped
// here so the workspace allow-list stays free of generated-code carveouts.
#![allow(clippy::trivially_copy_pass_by_ref, clippy::default_trait_access)]
#![allow(clippy::derive_partial_eq_without_eq, clippy::missing_const_for_fn)]
#![allow(missing_docs)] // Generated code.

tonic::include_proto!("grimoire.peer.v1");
