// Generated by tonic-build from `proto/worker.proto`. Lints below are scoped
// here so the workspace allow-list stays free of generated-code carveouts.
#![allow(clippy::trivially_copy_pass_by_ref, clippy::default_trait_access)]

tonic::include_proto!("grimoire.worker");
